import { Theme } from '../../types';

export const dark: Theme = {
  primaryColorUp: '#AA77FF',
  primaryFontFamily: 'Nunito, sans-serif',
  lightColorUp: '#FFFFFF',
  outlineColorDown: '#62CDFF',
  outlineColorUp: '#62CDFF',
  inputBackgroundColorUp: '#f00',
  inputBackgroundColorDown: '#EDF5FF',
  borderColorDown: '#31334F',
  lightColorDown: '#F2F2F2',
  primaryColorDown: '#AA77FF',
  textColorDown: '#FFFFFF',
  backgroundColorDown: '#0F172A',
  foregroundColorDown: '#0B0C14',
  foregroundColorUp: '#31334F',
  darkColorUp: '#1C1F2D',
  darkColorDown: '#353131',
  backgroundColorUp: '#0F172A',
  textColorUp: '#0B0C14',
  borderColorUp: '#31334f',
  warningColorUp: '#FFD700',
  secondaryColorDown: '#2591c4',
  secondaryColorUp: '#62CDFF',
  warningColorDown: '#FFA500',
  dangerColorUp: '#FF0000',
  dangerColorDown: '#8B0000',
  successColorUp: '#57C5B6',
  successColorDown: '#3da091',
  secondaryFontFamily: 'Ubuntu, sans-serif',
};
