import { Theme } from '../../types';

export const dark: Theme = {
  primaryColorUp: '#AA77FF',
  primaryFontFamily: 'Nunito, sans-serif',
  lightColorUp: '#FFFFFF',
  outlineColorDown: '#62CDFF',
  outlineColorUp: '#62CDFF',
  inputBackgroundColorUp: '#FFFFFF',
  inputBackgroundColorDown: '#EDF5FF',
  borderColorDown: '#EDEDED',
  lightColorDown: '#F2F2F2',
  primaryColorDown: '#AA77FF',
  textColorDown: '#1C1F2D',
  backgroundColorDown: '#DAF5FF',
  foregroundColorDown: '#D3DFFF',
  foregroundColorUp: '#f7f9ff',
  darkColorUp: '#1C1F2D',
  darkColorDown: '#353131',
  backgroundColorUp: '#FFFFFF',
  textColorUp: '#FFFFFF',
  borderColorUp: '#EDEDED',
  warningColorUp: '#FFD700',
  secondaryColorDown: '#57C5B6',
  secondaryColorUp: '#57C5B6',
  warningColorDown: '#FFA500',
  dangerColorUp: '#FF0000',
  dangerColorDown: '#8B0000',
  successColorUp: '#008000',
  successColorDown: '#006400',
  secondaryFontFamily: 'Ubuntu, sans-serif',
};
