import { Theme } from '../../types';

export const dark: Theme = {
  primaryColorUp: '#AA77FF',
  primaryFontFamily: 'Nunito, sans-serif',
  lightColorUp: '#FFFFFF',
  outlineColorDown: '#62CDFF',
  outlineColorUp: '#62CDFF',
  inputBackgroundColorUp: '#F4F7FF',
  inputBackgroundColorDown: '#FFFFF',
  borderColorDown: '#EDEDED',
  lightColorDown: '#F2F2F2',
  primaryColorDown: '#AA77FF',
  textColorDown: '#1C1F2D',
  backgroundColorDown: '#DAF5FF',
  foregroundColorDown: '',
  foregroundColorUp: '',
  backgroundColorUp: '#FFFFFF',
  textColorUp: '#FFFFFF',
  borderColorUp: '#EDEDED',
  warningColorUp: '#FFD700',
  secondaryColorDown: '#57C5B6',
  secondaryColorUp: '#57C5B6',
  warningColorDown: '#FFA500',
  dangerColorUp: '#FF0000',
  dangerColorDown: '#8B0000',
  successColorUp: '#008000',
  successColorDown: '#006400',
  secondaryFontFamily: 'Ubuntu, sans-serif',
};
